FROM node:24-alpine3.23

WORKDIR /app

COPY package*.json ./

RUN apk add --no-cache \
    python3 \
    make \
    g++ \
    cairo-dev \
    pango-dev \
    jpeg-dev \
    giflib-dev \
    librsvg-dev \
    curl \
    tar \
    git

RUN npm ci

COPY dist ./dist/

EXPOSE 3000

#CMD ["/bin/sh"]
CMD ["node", "dist/geo-composer.js", "-c","config/config.json" ]